# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

xcodeproj 'ARNZoomImageTransition.xcodeproj'

platform :ios, '8.0'
use_frameworks!

target 'ARNZoomImageTransition' do

  pod 'ARNTransitionAnimator'

end
